"""Initial migration

Revision ID: 123456789abc
Revises: 
Create Date: 2024-11-20 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = "123456789abc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawler_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sampling_rate", sa.Float(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("process_with_llm", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crawler_metadata")
    # ### end Alembic commands ###
