data "aws_ssm_parameter" "app_secrets" {
  for_each = toset([
    "redis_url",
    "anthropic_api_key",
    "auth0_client_id",
    "auth0_client_secret",
    "auth0_client_id_management",
    "auth0_client_secret_management",
    "auth0_domain",
    "aws_access_key_id",
    "aws_secret_access_key",
    "cased_api_auth_api_key",
    "cased_internal_slack_url",
    "cased_org_id",
    "cased_s3_bucket_name",
    "datadog_api_key",
    "datadog_app_key",
    "django_secret_key",
    "django_settings_module",
    "github_app_id",
    "github_app_name",
    "github_app_private_key",
    "github_app_secret",
    "github_client_id",
    "github_slack_channel_id_1",
    "github_webhook_secret",
    "helicone_api_key",
    "helicone_auth",
    "logtail_source_token",
    "loops_api_key",
    "openai_api_key",
    "openrouter_key",
    "psql_host",
    "psql_password",
    "psql_user",
    "resend_api_key",
    "sentry_dsn",
    "site_url",
    "slack_client_id",
    "slack_client_secret",
    "slack_signing_secret",
  ])

  name = "/${var.project_name}/${upper(each.key)}"
}